export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_RESULT = "USER_SIGNIN_RESULT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_RESULT = "USER_REGISTER_RESULT";

export const USER_DASHBOARD_REQUEST = "USER_DASHBOARD_REQUEST";
export const USER_DASHBOARD_RESULT = "USER_DASHBOARD_RESULT";
